import { DropdownOption } from '@/components/ui/SearchableDropdown';

export const UNIT_OPTIONS: DropdownOption[] = [
  { value: 'piece',  label: 'Piece' },
  { value: 'pcs',    label: 'Number / Pieces' },
  { value: 'kg',     label: 'Kilogram' },
  { value: 'kl',     label: 'Kilo' },
  { value: 'meter',  label: 'Meter' },
  { value: 'lm',     label: 'Linear Meter' },
  { value: 'liter',  label: 'Liter' },
  { value: 'box',    label: 'Box' },
  { value: 'pack',   label: 'Pack' },
  { value: 'pkt',    label: 'Packet' },
  { value: 'bag',    label: 'Bag' },
  { value: 'roll',   label: 'Roll' },
  { value: 'ctn',    label: 'Carton' },
  { value: 'ton',    label: 'Ton' },
  { value: 'trip',   label: 'Trip' },
  { value: 'sqm',    label: 'Square Meter' },
  { value: 'cbm',    label: 'Cubic Metre (cbm / m3)' },
  { value: 'pump',   label: 'Pump' },
  { value: 'sheet',  label: 'Sheet' },
  { value: 'brd',    label: 'Board' },
  { value: 'drm',    label: 'Drum' },
  { value: 'doz',    label: 'Dozen' },
  { value: 'ls',     label: 'Lump Sum' },
  { value: 'set',    label: 'Set' },
  { value: 'ream',   label: 'Ream' },
  { value: 'bundle', label: 'Bundle' },
  { value: 'nos',    label: 'Nos / Number' },
  { value: 'mtr',    label: 'Metre' },
  { value: 'qty',    label: 'Quantity' },
  { value: 'pair',   label: 'Pair' },
  { value: 'can',    label: 'Can' },
  { value: 'gal',    label: 'Gallon' },
  { value: 'day',    label: 'Day' },
  { value: 'hour',   label: 'Hour' },
  { value: 'month',  label: 'Month' },
];
